### PR TITLE
Feat/ci cd pipeline

### PR DESCRIPTION
**Pull request by abhishek-ws**
### Ticket Link

---

### Related Links

---

### Description

New ci.yml added for checking continuous integration on PR with master and feat/trackDetails-itunes
### Steps to Reproduce / Test

yarn test

### GIF's

---

### CODE REVIEW

**Comment by vishnu-wednesday** [comment]
Looks good. did you manage to test caching of dependencies?

**Comment by abhishek-ws** [comment]
I tried caching dependecies, but was unable to succeed in that part, so i shifted back to without cache config, as I assumed in real project PR, we will be only making PR and make CI run only after making sure everything works fine, and not frequently

**Comment by vishnu-wednesday** [comment]
What error did you get?

**Comment by abhishek-ws** [comment]
even after adding the cache step inside ci.yml, it didnt persisted the dependencies and they got installed again

**Comment by vishnu-wednesday** [comment]
Cache is temporary. If you are running one after the other in quick succession you see the impact of cached dependencies. See for an example : https://github.com/vishnu-wednesday/react-template/actions/runs/1229486171

**Comment by abhishek-ws** [comment]
Letme check and implement

**Comment by abhishek-ws** [comment]
Thank you for feedback, I have added the cache feature for ci.yml, now the whole ci test build time has been reduced even if I test 3 node envs at same time.

**Review by vishnu-wednesday — APPROVED** [review]

**Pull request merged**
